### ISSUE TITLE
Form is too slow to respond

### ISSUE THREAD

**Issue by numeranazneen** [OpenSRP/opensrp-client#101]
I was testing the FWNewHH form, the form is too slow. Specially when I tried to click '+' to add another member in the form, it takes almost 15-20 sec to appear the next section.

**Comment by numeranazneen** [comment]
@cagulas  do you also get the same problem?

**Comment by cagulas** [comment]
@numeranazneen I haven't so far, but probably because I'm using Genymotion for testing instead of a real tablet.  I think I told @raihan-mpower before that I am unable to access the app settings button on the login screen on my Samsung Galaxy Tab, so the only way I can test the app is to install it on my Genymotion.  This is related to the Enketo performance issue, which @koros is working on now.
