### ISSUE TITLE
New icon requests for Thrive Pakistan apk

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#114]
We will require the following icons for the development of our application:

1) Third gender
2) Woman register
3) Field and Monitoring register
4) Pakistani woman placeholder 
5) QR code icon

**Comment by rowo** [comment]
From Wajeeha Raza: 

**1) Third gender - As a baby icon? As a placeholder avatar in the registers?**
For now, we will only need this as a baby icon in the vaccinator register, but eventually we will probably need a third gender placeholder avatar for the Household register for Lady Health Workers.

**2) Woman register - On the home screen**
Yes, the woman register will be on the home screen. This is where the vaccinator will record information about TT vaccinations given to women.

**3) Field and Monitoring register - On the home screen (what is the content/theme of this register?)**
The field and monitoring register is also on the home screen. For the vaccinator, this register will contain the stock forms so that the vaccinator can report the number of vaccines received and the number of vaccines that were wasted. For the Lady Health Worker, this register will contain their monthly reports from (i) their work, (ii) the female volunteers health meetings and (iii) the male volunteers health meetings.

**4) Pakistani woman placeholder - Avatar image?**
The Pakistani woman placeholder would be an avatar image required for the woman register used by the vaccinator for TT vaccinations. This will also be used in the navigation window.

**5) QR code icon - In the navigation**
The qr code icon is present in the navigation for both the Woman register and the Child Register.

**Vaccinator Module mockups: https://drive.google.com/open?id=0B6FoJQBPvu7eYjYwVDMwcnBjQWc&authuser=0**

**Comment by rowo** [comment]
1) So third gender is something that will go into this icon category? 
<img width="114" alt="screen shot 2015-11-16 at 1 31 39 pm" src="https://cloud.githubusercontent.com/assets/1584163/11190946/7511791c-8c66-11e5-9535-0b99a0d6aff6.png">

2) Should the icon be more general, i.e. for TT or adult female vaccines, rather than just "Women" in general. For example it could be a woman with a shot. Just a woman is fine though.

3) Do these have to be the same icon or can they be different depending on the user? If same is easier to build, that's fine.

4) Is this the equivalent of the below but for muslim women?
![woman_placeholder](https://cloud.githubusercontent.com/assets/1584163/11191077/54ebde10-8c67-11e5-9c4a-9fa5a1614efe.png)

**Comment by wajeeharaza** [comment]
**1. So third gender is something that will go into this icon category?**
Yes, exactly! Maybe a third gender nuetral colour like green or purple would be good.

** 2) Should the icon be more general, i.e. for TT or adult female vaccines, rather than just "Women" in general. For example it could be a woman with a shot. Just a woman is fine though.**
I think just a woman would be fine since we're using a simple child image for the child vaccine, having a woman icon for the woman register would appear more consistent.

** 3) Do these have to be the same icon or can they be different depending on the user? If same is easier to build, that's fine.**
I think the same icon would be great :)

**4) Is this the equivalent of the below but for muslim women?**
Yes, that is what I meant. Although a *Pakistani woman would be more accurate. So for example the woman in the picture appears to be wearing a sari, which is a dress associated with India. Women in Pakistan traditonally wear kurta shalwar with a dupatta. If you use the same image with the pink cloth on both shoulders instead of one, I think that would be great!

**Comment by rowo** [comment]
@wajeeharaza Here's one and two.

1) Green or purple make sense. Up to you.

![child_othergender2_infant](https://cloud.githubusercontent.com/assets/1584163/11291908/7a4fe566-8f14-11e5-9e64-cf72f4d49d93.png)
![child_othergender_infant](https://cloud.githubusercontent.com/assets/1584163/11291909/7a4fc9f0-8f14-11e5-9937-f363a3f29bf4.png)


2) Just a woman seems reasonable.

![register-women](https://cloud.githubusercontent.com/assets/1584163/11291903/6e46b862-8f14-11e5-94f5-ec5e11b02cca.png)

**Comment by ahmedihs** [comment]
hi @rowo , so far woman register icon is great . is it possible ?? you create this one now until they decide about child icon .

**Comment by wajeeharaza** [comment]
hi @rowo both icons are great, thanks!
I asked my team and they preferred the purple icon for the third gender child so we'll be going with that one.

**Comment by rowo** [comment]
@wajeeharaza Sounds good. Looking at tasks 3 and 4. The above images you can just grab and save, they should be usable.

**Comment by ahmedihs** [comment]
@rowo actually the 2 icon which is for woman register , isnot of  accurate size for the Register images.

**Comment by rowo** [comment]
@ahmedihs Oops sorry. Would you mind sharing another register image asset so I can make sure to match it up?

**Comment by ahmedihs** [comment]
@rowo 
![register_pnc](https://cloud.githubusercontent.com/assets/11191881/11522632/05de05ac-98db-11e5-89a6-b33052958082.png) this is the image.

**Comment by rowo** [comment]
@ahmedihs Hi sorry for the delay. The images are the same size.

**Comment by ahmedihs** [comment]
okay thanks @rowo  but still we need field and monitor Register icon

**Comment by rowo** [comment]
A monitoring register:

![monitoring-register](https://cloud.githubusercontent.com/assets/1584163/11799730/aaa11520-a2a4-11e5-8f12-f9e437cbfcb7.png)

**Comment by ahmedihs** [comment]
thanks @rowo  , just one more Pakistani woman placeholder icon .

**Comment by rowo** [comment]
@ahmedihs here's a woman placeholder avatar:

![pakistani_woman](https://cloud.githubusercontent.com/assets/1584163/11845170/931c454a-a3e0-11e5-9306-7cd777fa2bb3.png)

I think remaining is a QR code icon for the top bar (like below), is that correct?

![screen shot 2015-12-16 at 10 36 07 am](https://cloud.githubusercontent.com/assets/1584163/11845228/d9922526-a3e0-11e5-90d7-98e13d4eb130.png)

**Comment by ahmedihs** [comment]
thanks @rowo  there is no need for qrcode icon , we already have added it .
