### ISSUE TITLE
Woman avatar image is pixelated

### ISSUE THREAD

**Issue by ahmedihs** [OpenSRP/opensrp-client#122]
Hi @rowo  , 

woman avator in app is getting pixelated . please provide image with higher res .

**Comment by rowo** [comment]
@ahmedihs Is there a specific resolution you need? The original file was 600x600 at 72dpi for reference. 

I can also send an .eps or .ai file if you can use that.

**Comment by ahmedihs** [comment]
make it in 120X120 , 240X240 and one with higher then 600

**Comment by rowo** [comment]
Anything specific higher than 600? 640x640 ok?

**Comment by ahmedihs** [comment]
so there isnt any specific . 640X640 can work

**Comment by rowo** [comment]
Here are the files. So was it pixelated because the app was scaling the image down instead of being "native" resolution?

![woman-avatar-120](https://cloud.githubusercontent.com/assets/1584163/12183527/53549910-b55d-11e5-8d12-0f5966976558.png)
![woman-avatar-240](https://cloud.githubusercontent.com/assets/1584163/12183529/5397c050-b55d-11e5-9831-6559ef38cf43.png)
![woman-avatar-640](https://cloud.githubusercontent.com/assets/1584163/12183528/535717c6-b55d-11e5-8593-76971309884e.png)

**Comment by ahmedihs** [comment]
i think image is scaled down  but i thought that it could be better to have one with higher resolution if low resolutions image dont work .

**Comment by rowo** [comment]
Cool. Just asking since the original was already 600x600 and you mentioned it was showing up pixelated.

**Comment by cagulas** [comment]
In latest PK apk, the woman avatar is still pixelated.  @MohammadSafwan did the above higher res images not work?
