### ISSUE TITLE
The start and end times should appear correctly on the submitted data

### ISSUE THREAD

**Issue by koros** [OpenSRP/opensrp-client#123]

**Comment by cagulas** [comment]
Since start and end times are working correctly for Enketo on Ona, this is likely due to adjustments we made in terms of how the form gets submitted in OpenSRP.  @koros is looking into this.

@numeranazneen it would be helpful for us to know whether this was working previously and recently broke, or if this is the first time it was noticed.

**Comment by numeranazneen** [comment]
Sorry...we didn't check this previously :(  but recently when we are able to export data, we check the csv files and found that it's showing all same dateTime in both start and end.

**Comment by koros** [comment]
@numeranazneen, The issue should be fixed now, please confirm on you end

**Comment by numeranazneen** [comment]
Thanks @koros we'll check and let you know the test result.
