### ISSUE TITLE
Remove auto data population option for unsaved form

### ISSUE THREAD

**Issue by numeranazneen** [OpenSRP/opensrp-client#257]
Forms are showing the data fields repopulated by data that was put in for the previous submission of the form. Even if the previous form was successfully submitted/synced with server it was still populating those data in new form. This happens for almost half of the FWAs case, but we couldn't regenerate it, because it's not happening all the time. 

It would be great to have this option if we can fix this issue, but as it's urgent to launch the project in field and this is kind of blocker for them so it's better for now to remove this option.

@cagulas @sohelsarder

**Comment by cagulas** [comment]
Just to confirm, there is a confirmation message that asks them to confirm they want to leave the form, correct? 

Agree this would be a useful feature, so that health workers can return to a form to fill in rest of details later. @numeranazneen can you create a new feature request issue about this with the use case and status of the feature?

**Comment by raihan-mpower** [comment]
this feature has been made optional and we have blocked it in our deployment to prevent the bug from reoccuring

**Comment by numeranazneen** [comment]
:(
