### ISSUE TITLE
[EC reference app] Ensure child registration sync to Aleena is immediate

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#280]
When you register a child in PK vaccinator app then try to look up the child in Aleena, sometimes there is a significant delay (a few minutes), and the error is returned that matching child ID cannot be found. Please investigate why there is a delay and make sure the sync to Aleena is immediate.

**Comment by maina** [comment]
@cagulas This happens because vaccinator app submits a formsubmission to the server which must be converted to EC which is the data model used by aleena. This happens through a repeating task that runs  every 2 minutes. I've updated the code to fire this task immediately after a formsubmission is submitted but this doesn't totally make the record to be immediately available to aleena but rather a bit more faster.

**Comment by cagulas** [comment]
ok, thanks @maina makes sense.
