### ISSUE TITLE
BZ1.5 - Ability to add demographic info

### ISSUE THREAD

**Issue by mberg** [OpenSRP/opensrp-client#303]
**Importantly** we need to be able to also allow edits

Personal information-entered into the system includes identification data such as:

- First name (optional) Family name
- Mother (ref. or name)
- Place of birth (ref.)
- National ID (e.g. birth certificate) (OPTIONAL) Immunization ID / barcode
- Gender
- Date of birth
- Contact information (e.g. mother/caregiver mobile phone, village/street )
- CHW/volunteer phone
- Caregiver name

Requirements to finalize @cagulas 

- [x] List of specific things they will capture
- [ ] We need to discuss how the mother / caregiver is handled.  Are they a separate person in a system?  Ie) can multiple children be linked to the same woman or do we manually enter in each one

**Comment by cagulas** [comment]
See birth registration form in data dictionary [here](https://docs.google.com/spreadsheets/d/1luD3r_1AQaCn6W-WlgtXilf5PyHJo8qgqZk4FVHxT8w/edit#gid=0). 

The **Editable** column shows whether the field should be editable in the app after birth registration form is submitted.

DOB (`Date_Birth`) is entered and age of the child should be automatically calculated and displayed in a note field according to certain age cutoffs:

From age 0 days to 13 days - In days
From age 14 days to 13 weeks, 6 days - In weeks and days
From age 14 weeks to 51 weeks, 6 days - In months and weeks
From age 1 year - In years and months

In the birth registration form, first name (`First_Name`) of the child is optional. This is because children are not usually named at birth. If `First_Name` is left blank when birth registration form is filled, it should be automatically calculated as "B/o `Mother_Guardian_Name`"

The health worker can edit this field later and add the baby's real name.
