### ISSUE TITLE
BZ1.7a Online: Ability to record immunizations from children who are from other villages

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#306]
Need to confirm whether this would be an online lookup where the health worker searches a central database for the child and syncs to her tablet to update the record. What about record merge?

**Comment by mberg** [comment]
Yes - by other village I think this is what they mean. Other village
basically means other health facility.

So yes online search and then assigning that patient to the new health
facility so it then sinks.

**Comment by cagulas** [comment]
Health worker can do a global search in the app (with a data connection) and can sync child records to her device. Once synced, she can record vaccines.

@rowo we'll need a mockup to show the list of children in the search results and how the health worker can select the children she wants to sync to her device.

**Comment by rowo** [comment]
@cagulas Are you able to sync records that aren't in your catchment area? I figured the list just shows you the matching people (ordered by last name). Then you can click on their cards. To get them to sync you have to change their areas to match your own... only then would it sync. Otherwise, you can just fill out their cards if you are providing services and it doesn't sync to the device.

**Comment by cagulas** [comment]
@maina Can you see a child's card and fill out services for them (vaccines, weight) without syncing the child's record to your device?

@rowo In order to assign a kid to your area (from the detailed view) wouldn't you need to sync the record to your device first?

**Comment by maina** [comment]
Not possible, you would have to sync the child records to see their vaccine card. However, you could fill out services provided to them without having to sync their records as long as they've their zeir id if this functional requirement #408 works....
