### ISSUE TITLE
BZ2.1 Enforce field validation to refer to a reference table of pre-populated values (e.g., villages within health facility capture radius or within the country)

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#312]
Ability to allow administrator to pre-populate names of communities served by each facility.

Done via DHIS2? If so, this is the same requirement as BZ2.

**Comment by mberg** [comment]
Yes it's the same.  We can merge these.

We'll use our own DHIS2 instance since the MOH one in Zambia only goes to
facility level and we need to go down to village and potentially
sub-village level.

If we are using enketo we need to see how the pulldowns will be created or
we need to use an approach similar to what Bangladesh did with their drill
down UI.

**Comment by cagulas** [comment]
Closing this, merging this requirement under https://github.com/OpenSRP/opensrp-client/issues/311
