### ISSUE TITLE
Implement mother lookup functionality 

### ISSUE THREAD

**Issue by maina** [OpenSRP/opensrp-client#421]
Mother lookup involves searching the local device for mother(s) with a matching `Mother_Guardian_First_Name`, `Mother_Guardian_Last_Name`, and `Mother_Guardian_Date_Birth` (when given). On finding a match(es), 'mother/guardian match found' (a toast with a customized layout https://developer.android.com/guide/topics/ui/notifiers/toasts.html) is displayed whereby on click  a popup is displayed with the mother's name and her children name.  The user selects an existing mother whose base_entity_id is added to the child document as a relationship. There should also be a cancel option, or tap out of the modal if there is no match confirmed. If there is a match, the relationships in OMRS should be created as well (parent/child and sibling/sibling, as appropriate).

![form-lookup](https://cloud.githubusercontent.com/assets/360650/23704744/636cff54-0417-11e7-9fb8-748939b18e97.png)

**Comment by rowo** [comment]
@keymane @cagulas 

My take on this: 
<img src="https://cloud.githubusercontent.com/assets/1584163/25259894/cb4d2e2a-2616-11e7-8698-b0bedfc75d19.png" width="520px">

- This is about mother matches so I think the first/last names should match
- All of those ID numbers don't seem needed in this context. I think the sequence of matching up goes: look at birthdate, if that doesn't help look at children info — names and/or number of kids. If two mothers match up in all of those things, only then might children ages make sense — so if that is a reasonable scenario (i.e. where all of those match) we can add those in after each child's name.

Notes on what's going on:
<img src="https://cloud.githubusercontent.com/assets/1584163/25260058/a744f8e0-2617-11e7-9b1a-dfc757461191.png" width="520px">

**Comment by cagulas** [comment]
@rowo This looks great. Three comments/questions: 1) Do they tap on the row to select? Is this obvious enough? 2) Once they tap on the row to select, how will they see what they have selected in the form? 3) To cancel, do they just tap anywhere outside the box?

**Comment by rowo** [comment]
@cagulas 
1. I think it's clear since it's a popup list sort of like a menu, but it can be something to try out informally vs. another option with a button like Eph had before. Let me know if that's possible during your current trip — even informally with people on the Path team that haven't seen it. So I'd go through the sequence with 4–5 people with the registration flow, then the yellow popup appears and they click.. and then this screen shows up. Do they know what to do from there? Then do the same thing with another group and let me know which one was good.
2. That's a great question. I'm not sure. To be most obvious we'd have to show all of the same info in the form, but that may be a technical challenge. If so, there could be a temporary icon associated with each name and that gets inserted into the form. This might require a conversation with someone familiar with the registration form. This name would need to be clickable to make an edit.
3. Tapping out of the box — yes, that's what I was thinking. Treating it like a popup like the location selection, a [simple dialog](https://material.io/guidelines/components/dialogs.html#dialogs-simple-dialogs). However, looking at it again maybe it should be more like a [confirmation dialog](https://material.io/guidelines/components/dialogs.html#dialogs-confirmation-dialogs).

**Comment by keymane** [comment]
@rowo Looks good. Yea, a simple dialog would work

**Comment by rowo** [comment]
@keymane I think we should test the simple dialog vs. confirmation dialog like described in https://github.com/OpenSRP/opensrp-client/issues/421#issuecomment-296175206. I can make another screen if @cagulas thinks they have some time to go through it in Livingstone. 

@keymane What do you think about what can show up in the registration form when you've selected someone? How customizable is the field? At the most minimal end, we can use the name and a random glypth (so all text based) and text color. At the most minimal, we reproduce the entire selected line object as seen in the popup. I think at the very least, we need to indicate that this person was an existing mother and isn't going to be a new mother.

**Comment by rowo** [comment]
@cagulas @keymane 
Here's an updated version that allows for more child names to be shown, which most of the time will be the differentiator. Having an actual child lookup to find the mother would be faster than this lookup process.

<img src="https://cloud.githubusercontent.com/assets/1584163/25320127/55bbc73a-2872-11e7-918d-b9f85cd9cee3.png" width="520px">

**Comment by keymane** [comment]
@rowo  I'll test both the simple and confirmation dialog. After selecting, `Mother_Guardian_First_Name`, `Mother_Guardian_Last_Name`, and `Mother_Guardian_Date_Birth` can be updated with values from the selected mother.
