### ISSUE TITLE
Implement no matching person dialog fragment

### ISSUE THREAD

**Issue by maina** [OpenSRP/opensrp-client#422]
This dialog is displayed when scan qr code in the home screen #398 doesn't find a matching record in the local db.
- [x] Search out of catchment records-  opens advanced search screen #407
- [x] Record out of catchment service- opens record out catchment area screen #408
- [x] Cancel -closes the dialog

![no-matching-person](https://cloud.githubusercontent.com/assets/360650/23705078/fbe76a34-0418-11e7-8dad-f811dd8b3a0c.png)

**Comment by cagulas** [comment]
For the advanced search, would it just populate the ZEIR ID automatically and the user still has to select the search button, or would it populate the ZEIR ID and also automatically do the search as well? If they're scanning a QR code, only ZEIR ID is required for the advanced search, since it's unique, so I guess it would make sense for them to bypass the advanced search screen and go straight to the results. Thoughts?
