### ISSUE TITLE
Update out of catchment form with age, gender, vitamin a, deworming, ITN services

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#495]
In order to include out of catchment services in HIA2 reporting, we have to capture the child's age and gender in the form (since a lot of the HIA2 indicators are disaggregated by age and gender) as well as add new service options for Vitamin A, deworming, and ITN.

If offline, the user will have to fill age and gender manually; if online, the app can pull in age and gender automatically from the advanced search results.

Assigning to myself for now, as I'll update the data dictionary first before tech picks up this issue.

**Comment by cagulas** [comment]
Data dictionary updated, see rows highlighted in yellow [here](https://docs.google.com/spreadsheets/d/1luD3r_1AQaCn6W-WlgtXilf5PyHJo8qgqZk4FVHxT8w/edit#gid=1173845481). 

@jasonrogena let's chat quickly about this when you have a few minutes.

**Comment by maina** [comment]
- [ ] using zeir_id ,gender and age as a record in ec_child table if one doesn't exist when recording out of area services 
- [ ] add child_id column to weights and vaccines table as a foreign key to the child so that it's easy to uniquely match weight/vaccine records with the client even when base_entity_id is not known

**Comment by faith-mutua** [comment]
This issue was moved to OpenSRP/opensrp-client-path#41
