### ISSUE TITLE
Add recurring services to under 5 history tab

### ISSUE THREAD

**Issue by maina** [OpenSRP/opensrp-client#499]
- [x] Add "RECURRING SERVICES" section in the "Under Five History" tab right below the "IMMUNISATIONS" section. Either of Vitamin A, Deworming or ITN subsection is added only when the service is given otherwise remains blank if the child hasn't received any of these services.
- [x] Add "Edit recurring services data" menu item below the Edit immunisation data menu item in the profile details page menu. Upon selecting this option, an "Edit" button appears next to each Vitamin A, Deworming, and ITN service in the recurring services section on the page. 
- [x] Selecting any of the edit buttons opens the Edit modal for the service similar to the vaccine edit modal

- [x] Under 5 History view
![232284700](https://cloud.githubusercontent.com/assets/3488986/25839929/6beee6d6-34a2-11e7-8e93-6b27ddf96260.png)

**Comment by cagulas** [comment]
For the edit interaction, Vitamin A and Deworming will work exactly the same as the vaccines, i.e., you can either undo the service or change the service date.

For ITN, however, it's a bit different, since the interaction is a 3-question flow. After discussing with @rowo, we feel to make things simple, we should show the same 3-question flow, with the answers filled in as before.

**Comment by cagulas** [comment]
This is done, closing this.
