### ISSUE TITLE
OpenSRP app designs 

### ISSUE THREAD

**Issue by ndisha** [OpenSRP/opensrp-client#50]
@rowo am uploading the current OpenSRP app screenshots that @raihan-mpower sent earlier. We need your help to improve the app appearance possibly by tomorrow? We have our demo on Thursday 8am (your time).

* [x] Homescreen:

![homescreen](https://cloud.githubusercontent.com/assets/801106/7812117/2f2de2b4-03b8-11e5-934b-ad0aac95c2e0.png)

* [x] HH-Register:

![hh_register_screen](https://cloud.githubusercontent.com/assets/801106/7812128/41444a24-03b8-11e5-8a28-ce89306d1f90.png)

* [x] HH-Register with picture of the HH head taken:

![hh_register_screen_with_image](https://cloud.githubusercontent.com/assets/801106/7812366/363db582-03ba-11e5-96e4-735abebe5476.png)

* [ ] Inhabitants page:

![inhabitants page](https://cloud.githubusercontent.com/assets/801106/7812368/3ff1f3a4-03ba-11e5-9885-1a569bb502dc.png)

* [ ] ELCO page:

![elcopage](https://cloud.githubusercontent.com/assets/801106/7812372/45e7e70a-03ba-11e5-839d-f366894c8c62.png)

**Comment by rowo** [comment]
@ndisha @raihan-mpower here's some feedback.

**Registers (ELCO, HH with photos, HH with placeholder avatars)**

Is there a reason why the HH with photos is so different from the ELCO and HH with placeholder avatars? Anyways, I just based my feedback on comparing Dristhi with the HH with photos, since that was the closest (so just make the others match up). I overlaid and offset Dristhi on top of the OpenSRP register too, hopefully that can help identify some mismatches, which are mainly around type size and margins.

![opensrp-hh](https://cloud.githubusercontent.com/assets/1584163/7816713/f58b18ac-039d-11e5-9dc5-8d0f96d24cf0.jpg)

**Home screen**

Mainly spacing and sizing issues here. Again, there's an overlay to make it easier to spot differences.

![opensrp-home](https://cloud.githubusercontent.com/assets/1584163/7816706/ed9066d4-039d-11e5-92ef-3e7451887b25.jpg)

**HH Member Details**

I'm actually a bit confused about this screen. I would replicate the styling from the register view (not quite sure the reasoning on the ID number coloring, but if you are going to do it, might as well go all the way). 

![opensrp-hhdetails](https://cloud.githubusercontent.com/assets/1584163/7817004/d1f53970-039f-11e5-8f71-a7c6d56226b5.jpg)

**Comment by rowo** [comment]
@ndisha closing this.
