### ISSUE TITLE
Implement offline vaccines schedules date validation functionality

### ISSUE THREAD

**Issue by maina** [OpenSRP/opensrp-client#500]
Currently the client app only enables "at birth" vaccines in the vaccine card when offline and the rest only after syncing alerts from the server. This functionality is to allow recording of all vaccines when offline i.e checking the time constraints that need to met based either on the dob or the various vaccines series logic. 
- [x] In the vaccine card functionality, add functionality to check if a vaccine is due based on the respective dates if no alert exists for the vaccine in the alerts table. e.g to enable penta1 button query the alerts table to see if any alert exists for the vaccine and if none exists with the status as either due or overdue, using the child's dob and the device time, evaluate if the vaccine is due by checking that the current device time is >=Child's DOB + 6 weeks. In most vaccines a similar check is applied by changing the reference date to either dob or the date the previous vaccine in a series was given except for OPV 4 whereby an extra check is done to confirm that OPV 0 was not given and OPV 3 was given at least 4 weeks ago. See vaccines schedules here https://docs.google.com/spreadsheets/d/1qB7kVl5M9CpTw8m4VRE5TjRpGdK996yXDWnHZdysWD0/edit#gid=0

Since this functionality entirely depends on the device time, as an enhancement add extra functionality to try and validate the device time as follows:
- [x] A check when the user first logs in to confirm that the device time is same as the server time. Depends on https://github.com/OpenSRP/opensrp-server/issues/259
- [x] Add `Intent.ACTION_TIME_CHANGED` and `Intent.ACTION_TIMEZONE_CHANGED` broadcast listener to listen on time/zone changes in the device and logout the user when the device time is changed to force a confirmation from the server that the new time/zone is the expected one.

**Comment by cagulas** [comment]
@maina Can we display an error on login fail that notifies the user the date/time settings are incorrect and they need to change the settings to be able to login again? I think the message can be something like the below:

"Log in failed."

"Please check that your device has the correct date/time settings. Go to settings."

If possible, it would be good to hyperlink the word "settings" above to go to the device's date/time settings page. If not possible, don't include the "Go to settings" sentence in the message.

**Comment by cagulas** [comment]
@maina I noticed that a user can record vaccines before the due date and even before the child's DOB - For e.g., child Yasmin Smith (ZEIR: 23400) in the biddemo tester account has DOB of May 18, 2017, but I was able to record her birth vaccines on April 18, 2017. As part of the implementation of offline schedules, can we make sure that date constraints when recording a vaccine are added?

**Comment by jasonrogena** [comment]
@cagulas I have added a simple date check (vaccines cannot be offered before the date of birth and past today)

**Comment by cagulas** [comment]
@jasonrogena This looks awesome. Great work. Constraints are working perfectly, but I noticed three minor issues:

- I wasn't able to record Measles 2 initially. Here is what I did: I registered a new kid who was 4 years old (DOB: 30-5-2013). I recorded MR 1 at 9 months of age (27-2-2014). I tried to record Measles 2 exactly 9 months after MR 1 (27-11-2014) but got an error snackbar message saying "Can't record Measles 2". The next time I open the modal, I notice the choice is only Measles 2 and MR 2 disappeared as a choice. This shouldn't happen. Also, the date widget seems to have lost the constraint as well, because I'm able to scroll back to the child's DOB now (30-5-2013). I tried to select DOB as the vaccine date and got the snackbar error message again: "Can't record Measles 2". This is correct, because I shouldn't be able to record vaccine date as DOB, but it shouldn't have let me scroll all the way back to DOB. Finally, when I try again and select "Vaccination done today", I'm able to record it. So, I should have been able to record it at 9 months after MR 1, but somehow I wasn't able to.

- After I finished all the testing, I went and changed the device's timezone in settings. I was logged out of the app with the message "The device's timezone changed. Please login again". I was able to login again right away. Shouldn't I be prevented from logging in, since my timezone is incorrect?

- Very quickly, on the message above "The device's timezone changed. Please login again". Please add a period to the end of the sentence.

**Comment by jasonrogena** [comment]
Fixing the Measles 2/MR 2 issue

"_After I finished all the testing, I went and changed the device's timezone in settings. I was logged out of the app with the message "The device's timezone changed. Please login again". I was able to login again right away. Shouldn't I be prevented from logging in, since my timezone is incorrect?_"
In the debug app, we've disabled timezone checking. Sorry, I'll build the app again for release so that you can QA that.

"_Roger Kilome's data is inconsistent (used that child to test out the schedules), but I'll make it such that the app doesn't crash if it ever gets such type of data_"

**Comment by cagulas** [comment]
Closing. Think everything has been addressed or fixed in other issues.
