### ISSUE TITLE
Alternative color scheme for 'due' reminders

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#58]
@rowo BD team suggests yellow to represent 'due' status as opposed to the current dark blue.  Pls advise.

**Comment by rowo** [comment]
@numeranazneen Here's a yellow you can use (with black text): #fdd835

- I'm actually not to clear on the purpose of this change. Is it due to training and having to say "light blue" and "dark blue" or is it worrying about people actually perceiving light vs. dark blue? 
- Does yellow have any significance culturally? Do street signals follow any pattern, or would it not matter to your users? Yellow to the western world communicates "caution" which I don't think is the right message. Blue was actually the original color with light blue signifying a button that is available but not really due, so maybe you can consider replacing that button color to something else if you are worried.
- What happens to the Edit button color? Is that still blue and then only scheduled dark blue's get changed? I can see that as justification for the color change.
- Adding a whole new color might get a little noisy. Might want to test this a bit.

**Comment by numeranazneen** [comment]
good question. In one of our initial meetings with JHU while we were saying Dark Blue/Light Blue to describe the scheduling thing, it  was making us confused. So, we thought it would make the Field workers more confused. That was the reason to change the color. 
As far I know for BD perspective, yellow is mostly used as a transitional color. So, between (Light) Blue and Red we thought to put a Yellow. Which will mean a transition from Not Yet Due (light Blue)->Post Due(Red), that is Due (Yellow). 
Another thing is, Red, Green and Yellow are the three most popular colors in BD. So, we came up with the suggestion of Yellow while we thought of using another color instead of two Blues. We could have used Red, Blue and Green, in that case there will be a perceiving issue. Because a few of the Field workers will not be able to make any difference between Blue and Green. While we will instruct them anything using the color code, there will be chance of making mistakes due to misperception.  

I am sorry, I don't know how to use the color text that you just mentioned. Can you please add that in your Mockup sample document, so that I can just copy and paste that to our document?

Thanks for your help and suggestions.

**Comment by rowo** [comment]
@numeranazneen Ok thanks for the explanation. Here is more info on the color: http://www.color-hex.com/color/fdd835. Let me know if that link gives you what you need.
