### ISSUE TITLE
gps widget - on the latest opensrp app (opensrp-app_22_09_2015.apk)

### ISSUE THREAD

**Issue by ndisha** [OpenSRP/opensrp-client#89]
@raihan-mpower on my tablet, the gps widget seems to be broken. I cant pick the coordinates therefore I cant save the forms in order to complete my tests. See below screenshots:

![screenshot_2015-09-25-10-50-54](https://cloud.githubusercontent.com/assets/801106/10103889/2aa37414-63af-11e5-91f1-c6f9e651cd51.png)
![screenshot_2015-09-25-10-53-20](https://cloud.githubusercontent.com/assets/801106/10103888/2a9ef150-63af-11e5-95f3-884ee730f183.png)

Is it happening for me only? @numeranazneen? Please check this out!

**Comment by numeranazneen** [comment]
We used SIM cards in our Tablet, so we are not getting this kind of error. Is it for the first time that you are trying to collect GPS using that tablet? I think for first time use, you should use a SIM card to get the GPS data and later on it'll cause such issue without SIM cards. 

obviously @raihan-mpower can explain the root cause better than me. But as he is on leave, so meanwhile you can try out my suggestion.

**Comment by ndisha** [comment]
Seems location was disabled on the tablet I was using to test, thats why it was not able to pick the coordinates. @raihan-mpower will work on popping up a message if GPS is disabled to alert the user to enable GPS to be able to get coordinates.

**Comment by ndisha** [comment]
@raihan-mpower also added a feature that checks if location is enabled on the tablet and notifys the user! Thanks!
